name: Build on push
run-name: "${{ github.ref_name }}: ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main
      - wrynose

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build-yocto.yml
